import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { DataProvider } from "../context";

const roboto = Roboto({ weight: "400", subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <DataProvider>
        <body className={roboto.className}>{children}</body>
      </DataProvider>
    </html>
  );
}
